version: "3"
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ./web:/usr/share/nginx/html
      - ./nginx/log:/var/log/nginx
      - ./nginx/etc/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/etc/conf.d:/etc/nginx/conf.d
    restart: always
  php:
    build: ./php
    image: php
    container_name: php
    restart: always
    expose:
      - 9000
    stdin_open: true
    tty: true
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./web:/var/www
      - ./php/etc/php.ini:/usr/local/etc/php/php.ini
      - ./php/etc/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf
  mysql:
    image: mysql:8
    restart: always
    privileged: true
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - ${MYSQL_DIR}/data:/var/lib/mysql
      - ${MYSQL_DIR}/etc:/etc/mysql/conf.d
      - ${MYSQL_DIR}/log:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    container_name: mysql
  redis:
    image: redis:4
    container_name: redis
    restart: always
    ports:
      - ${REDIS_PORT}:6379
    environment:
      TZ: Asia/Shanghai
    command: ["redis-server","/etc/redis/redis.conf"]
    volumes:
      - ./redis/data:/data
      - ./redis/etc:/etc/redis
